# Generated by Django 5.1.2 on 2024-11-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accountdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='update',
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='message',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
